version: "3.9"
services:
  graduation-f-node:
    build:
      context: .
    volumes:
      - type: bind
        source: ./src
        target: /data
    tty: true
    command: sh -c 'npm install --save --legacy-peer-deps && npm run dev'
    ports:
      - "3000:5173"
